package View;

import Control.Citem;
import Control.Cvenda;
import Dao.ItemDao;
import Dao.VendaDao;
import Model.Item;
import Model.Venda;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ListaVendaView extends javax.swing.JInternalFrame {

    int estoqueAtual;

    public ListaVendaView() {

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) tbl_ListaVendas.getModel();
        tbl_ListaVendas.setRowSorter(new TableRowSorter(modelo));

        limparTxtVenda();
        Cvenda.lerLista(tbl_ListaVendas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ListaVendas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_TipoItemVendido = new javax.swing.JTextField();
        lbl_TipoVenda = new javax.swing.JLabel();
        lbl_ValorVenda = new javax.swing.JLabel();
        txt_ValoItemVendido = new javax.swing.JTextField();
        btn_SelecionarItemVendido = new javax.swing.JButton();
        txt_QuantidadeItemVendido = new javax.swing.JTextField();
        lbl_QuantidadeVenda = new javax.swing.JLabel();
        btn_ConfimarEstorno = new javax.swing.JButton();
        btn_CancelarVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_ValorTotalVendido = new javax.swing.JTextField();
        txt_NomeItemVendido = new javax.swing.JTextField();
        lbl_NomeVenda = new javax.swing.JLabel();
        lbl_IdVenda = new javax.swing.JLabel();
        txt_IdItemVendido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_IdIDeVenda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Pesquisa = new javax.swing.JButton();
        txt_Pesquisa = new javax.swing.JTextField();
        combo_Tipos = new javax.swing.JComboBox();
        btn_RefreschCadastro = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbl_ListaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Venda", "Código", "Nome", "Tipo", "Quantidade Vendida", "Valor ", "Valor Venda", "Estoque Atual Loja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_ListaVendas);

        txt_TipoItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TipoItemVendidoActionPerformed(evt);
            }
        });

        lbl_TipoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TipoVenda.setText("Tipo:");

        lbl_ValorVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ValorVenda.setText("Valor:");

        txt_ValoItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ValoItemVendidoActionPerformed(evt);
            }
        });

        btn_SelecionarItemVendido.setText("Selecionar Item Vendido");
        btn_SelecionarItemVendido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_SelecionarItemVendido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_SelecionarItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelecionarItemVendidoActionPerformed(evt);
            }
        });

        txt_QuantidadeItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuantidadeItemVendidoActionPerformed(evt);
            }
        });

        lbl_QuantidadeVenda.setText("Quantidade Vendida:");

        btn_ConfimarEstorno.setText("Estornar Venda");
        btn_ConfimarEstorno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_ConfimarEstorno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ConfimarEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfimarEstornoActionPerformed(evt);
            }
        });

        btn_CancelarVenda.setText("Cancelar");
        btn_CancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor Total de Venda");

        txt_NomeItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeItemVendidoActionPerformed(evt);
            }
        });

        lbl_NomeVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NomeVenda.setText("Nome:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_ConfimarEstorno, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SelecionarItemVendido)
                        .addGap(39, 39, 39)
                        .addComponent(btn_CancelarVenda))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_QuantidadeVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_QuantidadeItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ValorTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(txt_NomeItemVendido))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_TipoVenda)
                                .addComponent(lbl_ValorVenda))
                            .addGap(68, 68, 68)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ValoItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_TipoItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(lbl_NomeVenda))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_NomeItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NomeVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_TipoVenda)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_TipoItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_ValorVenda))
                    .addComponent(txt_ValoItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ValorTotalVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_QuantidadeVenda)
                    .addComponent(txt_QuantidadeItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ConfimarEstorno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SelecionarItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lbl_IdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_IdVenda.setText("ID:");

        txt_IdItemVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdItemVendidoActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Venda:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_IdItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(txt_IdIDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txt_IdItemVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_IdVenda)
                    .addComponent(txt_IdIDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listagem de Vendidos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        btn_Pesquisa.setText("Pequisar");
        btn_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisaActionPerformed(evt);
            }
        });

        combo_Tipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Listar", "Mais Vendido", "Menos Vendido" }));
        combo_Tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_TiposActionPerformed(evt);
            }
        });

        btn_RefreschCadastro.setText("Refresh");
        btn_RefreschCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_RefreschCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_RefreschCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreschCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Pesquisa)
                            .addComponent(combo_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_RefreschCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pesquisa))
                        .addGap(31, 31, 31)
                        .addComponent(combo_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btn_RefreschCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisaActionPerformed
        selecao();
    }//GEN-LAST:event_btn_PesquisaActionPerformed

    private void combo_TiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_TiposActionPerformed
        btn_Pesquisa.setVisible(true);
        txt_Pesquisa.setText("");
    }//GEN-LAST:event_combo_TiposActionPerformed

    private void txt_IdItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdItemVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdItemVendidoActionPerformed

    private void txt_TipoItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TipoItemVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoItemVendidoActionPerformed

    private void txt_ValoItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ValoItemVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ValoItemVendidoActionPerformed

    private void btn_SelecionarItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelecionarItemVendidoActionPerformed
        buscarItemVendido();

    }//GEN-LAST:event_btn_SelecionarItemVendidoActionPerformed

    private void btn_ConfimarEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfimarEstornoActionPerformed
        estorno();
        deletar();
        

        Cvenda.lerLista(tbl_ListaVendas);
        limparTxtVenda();
    }//GEN-LAST:event_btn_ConfimarEstornoActionPerformed

    private void txt_NomeItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeItemVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeItemVendidoActionPerformed

    private void txt_QuantidadeItemVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuantidadeItemVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuantidadeItemVendidoActionPerformed

    private void btn_CancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarVendaActionPerformed
        limparTxtVenda();
    }//GEN-LAST:event_btn_CancelarVendaActionPerformed

    private void btn_RefreschCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreschCadastroActionPerformed
        Cvenda.lerLista(tbl_ListaVendas);
    }//GEN-LAST:event_btn_RefreschCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelarVenda;
    private javax.swing.JButton btn_ConfimarEstorno;
    private javax.swing.JButton btn_Pesquisa;
    private javax.swing.JButton btn_RefreschCadastro;
    private javax.swing.JButton btn_SelecionarItemVendido;
    private javax.swing.JComboBox combo_Tipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_IdVenda;
    private javax.swing.JLabel lbl_NomeVenda;
    private javax.swing.JLabel lbl_QuantidadeVenda;
    private javax.swing.JLabel lbl_TipoVenda;
    private javax.swing.JLabel lbl_ValorVenda;
    private javax.swing.JTable tbl_ListaVendas;
    private javax.swing.JTextField txt_IdIDeVenda;
    private javax.swing.JTextField txt_IdItemVendido;
    private javax.swing.JTextField txt_NomeItemVendido;
    private javax.swing.JTextField txt_Pesquisa;
    private javax.swing.JTextField txt_QuantidadeItemVendido;
    private javax.swing.JTextField txt_TipoItemVendido;
    private javax.swing.JTextField txt_ValoItemVendido;
    private javax.swing.JTextField txt_ValorTotalVendido;
    // End of variables declaration//GEN-END:variables

    public void limparTxtVenda() {
        txt_IdIDeVenda.setText("");
        txt_IdItemVendido.setText("");
        txt_NomeItemVendido.setText("");
        txt_TipoItemVendido.setText("");
        txt_QuantidadeItemVendido.setText("");
        txt_ValoItemVendido.setText("");
        txt_QuantidadeItemVendido.setText("");
        txt_ValorTotalVendido.setText("");
        txt_IdIDeVenda.setEnabled(false);
        txt_IdItemVendido.setEnabled(false);
        txt_NomeItemVendido.setEnabled(false);
        txt_TipoItemVendido.setEnabled(false);
        txt_QuantidadeItemVendido.setEnabled(false);
        txt_ValoItemVendido.setEnabled(false);
        txt_QuantidadeItemVendido.setEnabled(false);
        txt_ValorTotalVendido.setEnabled(false);
        btn_ConfimarEstorno.setEnabled(false);

    }

    public void selecao() {

//////////////////////////////////////////////////////////////////////////////////////        
        //Seleciona Metodo ler Lista e listar na tabela
        if (combo_Tipos.getSelectedItem() == "Listar") {
            Cvenda.lerLista(tbl_ListaVendas);
            System.out.println("seleção listar");

        }
//////////////////////////////////////////////////////////////////////////////////////
        //Seleciona Metodo Procurar por Mais Vendido
        if (combo_Tipos.getSelectedItem() == "Mais Vendido") {
            Cvenda.listarPorMaior(tbl_ListaVendas);

        }
//////////////////////////////////////////////////////////////////////////////////////
        //Seleciona Metodo Procurar por Mais Vendido
        if (combo_Tipos.getSelectedItem() == "Menos Vendido") {
            Cvenda.listarPorMenosVendido(tbl_ListaVendas);

        }


//        txt_IdItemVendido.setEnabled(false);
//        txt_TipoItemVendido.setEnabled(false);
//        txt_QuantidadeItemVendido.setEnabled(false);
//        txt_ValoItemVendido.setEnabled(false);
    }

    public void buscarItemVendido() {
        int row = tbl_ListaVendas.getSelectedRow();

        if (row != -1) {

            limparTxtVenda();
            txt_IdItemVendido.setText((String) tbl_ListaVendas.getValueAt(row, 0).toString());
            txt_IdIDeVenda.setText((String) tbl_ListaVendas.getValueAt(row, 1).toString());
            txt_NomeItemVendido.setText((String) tbl_ListaVendas.getValueAt(row, 2));
            txt_TipoItemVendido.setText((String) tbl_ListaVendas.getValueAt(row, 3));
            txt_QuantidadeItemVendido.setText((String) tbl_ListaVendas.getValueAt(row, 4).toString());
            txt_ValoItemVendido.setText((String) tbl_ListaVendas.getValueAt(row, 5).toString());
            txt_ValorTotalVendido.setText((String) tbl_ListaVendas.getValueAt(row, 6).toString());

            estoqueAtual = (int) tbl_ListaVendas.getValueAt(row, 7);
            btn_ConfimarEstorno.setEnabled(true);

            System.out.println(estoqueAtual);

        }

    }

    public void deletar() {

        int row = tbl_ListaVendas.getSelectedRow();

        if (row != -1) {
            
            Venda venda = new Venda();

            venda.setIdVenda((int) tbl_ListaVendas.getValueAt(tbl_ListaVendas.getSelectedRow(), 0));

            VendaDao.deletarVenda(venda);

            JOptionPane.showMessageDialog(rootPane, "Produto deletado com sucesso !", "Sucesso", JOptionPane.PLAIN_MESSAGE);
        }
    }

    public void estorno() {
        int row = tbl_ListaVendas.getSelectedRow();

        if (row != -1) {
            Item item = new Item();

            System.out.println("entrou no if doestorno");

            int estoqueEstorno = estoqueAtual + Integer.parseInt(txt_QuantidadeItemVendido.getText());
            System.out.println(estoqueEstorno);

            item.setId(Integer.parseInt(txt_IdIDeVenda.getText()));
            item.setNome(txt_NomeItemVendido.getText());
            item.setTipo(txt_TipoItemVendido.getText());
            item.setEstoque(estoqueEstorno);
            item.setValor(Double.parseDouble(txt_ValoItemVendido.getText()));
            ItemDao.alterarItem(item);
            JOptionPane.showMessageDialog(rootPane,
                "Estorno Realizado Com Sucesso realizada com sucesso !",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

           
        }

    }
}
