package View;

import Control.Citem;
import Control.Cvenda;
import Dao.ItemDao;
import Model.Item;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


 
public class VendaView extends javax.swing.JInternalFrame {

    int estoqueBaixa;

    //Collection<Item> listaEstoque = new ArrayList<>();
    /**
     * Creates new form CadastroView
     */
    public VendaView() {

        initComponents();
//
//        DefaultTableModel modelo = (DefaultTableModel) tbl_Lista.getModel();
//        tbl_Lista.setRowSorter(new TableRowSorter(modelo));
        Citem.lerLista(tbl_Lista);
        limparTxtVenda();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Lista = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_TipoVenda = new javax.swing.JTextField();
        lbl_TipoVenda = new javax.swing.JLabel();
        txt_EstoqueVenda = new javax.swing.JTextField();
        lbl_EstoqueVenda = new javax.swing.JLabel();
        lbl_ValorVenda = new javax.swing.JLabel();
        txt_ValorVenda = new javax.swing.JTextField();
        btn_SelecionarItemVenda = new javax.swing.JButton();
        txt_QuatidadeVenda = new javax.swing.JTextField();
        lbl_QuantidadeVenda = new javax.swing.JLabel();
        btn_ConfimarVenda = new javax.swing.JButton();
        btn_CancelarVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_IdVenda = new javax.swing.JLabel();
        txt_IdVenda = new javax.swing.JTextField();
        lbl_NomeVenda = new javax.swing.JLabel();
        txt_NomeVenda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Pesquisa = new javax.swing.JButton();
        txt_Pesquisa = new javax.swing.JTextField();
        combo_Tipos = new javax.swing.JComboBox();
        btn_RefreschCadastro = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbl_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Tipo", "Estoque", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Lista);

        txt_TipoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TipoVendaActionPerformed(evt);
            }
        });

        lbl_TipoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TipoVenda.setText("Tipo:");

        txt_EstoqueVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EstoqueVendaActionPerformed(evt);
            }
        });

        lbl_EstoqueVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_EstoqueVenda.setText("Estoque:");

        lbl_ValorVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ValorVenda.setText("Valor:");

        txt_ValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ValorVendaActionPerformed(evt);
            }
        });

        btn_SelecionarItemVenda.setText("Selecionar Item Para Venda");
        btn_SelecionarItemVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_SelecionarItemVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_SelecionarItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelecionarItemVendaActionPerformed(evt);
            }
        });

        txt_QuatidadeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuatidadeVendaActionPerformed(evt);
            }
        });

        lbl_QuantidadeVenda.setText("Quantidade venda:");

        btn_ConfimarVenda.setText("Confirmar Venda");
        btn_ConfimarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_ConfimarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ConfimarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfimarVendaActionPerformed(evt);
            }
        });

        btn_CancelarVenda.setText("Cancelar");
        btn_CancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarVendaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("*Campo Obrigatório");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_ConfimarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_CancelarVenda))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_TipoVenda)
                        .addGap(28, 28, 28)
                        .addComponent(txt_TipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_QuantidadeVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_QuatidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_EstoqueVenda)
                            .addComponent(lbl_ValorVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_EstoqueVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_SelecionarItemVenda))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TipoVenda)
                            .addComponent(txt_TipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_EstoqueVenda)
                            .addComponent(txt_EstoqueVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(txt_ValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_ValorVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_QuatidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_QuantidadeVenda)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(btn_SelecionarItemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ConfimarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lbl_IdVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_IdVenda.setText("ID");

        txt_IdVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdVendaActionPerformed(evt);
            }
        });

        lbl_NomeVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_NomeVenda.setText("Nome:");

        txt_NomeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_NomeVenda)
                        .addGap(18, 18, 18)
                        .addComponent(txt_NomeVenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txt_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IdVenda)
                    .addComponent(txt_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NomeVenda)
                    .addComponent(txt_NomeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Vendas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        btn_Pesquisa.setText("Pequisar");
        btn_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisaActionPerformed(evt);
            }
        });

        combo_Tipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Listar", "Nome", "Tipo", "Estoque Zerado", "Estoque Positivo", "Estoque Negativo" }));
        combo_Tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_TiposActionPerformed(evt);
            }
        });

        btn_RefreschCadastro.setText("Refresh");
        btn_RefreschCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btn_RefreschCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_RefreschCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreschCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(207, 207, 207)
                                    .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Pesquisa)
                                    .addComponent(combo_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_RefreschCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pesquisa))
                        .addGap(31, 31, 31)
                        .addComponent(combo_Tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btn_RefreschCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisaActionPerformed
        selecao();
    }//GEN-LAST:event_btn_PesquisaActionPerformed

    private void combo_TiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_TiposActionPerformed
        btn_Pesquisa.setVisible(true);
        txt_Pesquisa.setText("");
    }//GEN-LAST:event_combo_TiposActionPerformed

    private void txt_IdVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdVendaActionPerformed

    private void txt_TipoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TipoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TipoVendaActionPerformed

    private void txt_EstoqueVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EstoqueVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EstoqueVendaActionPerformed

    private void txt_ValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ValorVendaActionPerformed

    private void btn_SelecionarItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelecionarItemVendaActionPerformed
        buscarItemVenda();

    }//GEN-LAST:event_btn_SelecionarItemVendaActionPerformed

    private void btn_ConfimarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfimarVendaActionPerformed

        baixar();
        Cvenda.cadastrarVenda(txt_IdVenda.getText(), txt_NomeVenda.getText(),
                txt_TipoVenda.getText(), txt_QuatidadeVenda.getText(), txt_ValorVenda.getText(), estoqueBaixa);
        JOptionPane.showMessageDialog(rootPane,
                "Venda realizada com sucesso !",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        
        atualizatabela();

        limparTxtVenda();
    }//GEN-LAST:event_btn_ConfimarVendaActionPerformed

    private void txt_NomeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeVendaActionPerformed

    private void txt_QuatidadeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuatidadeVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuatidadeVendaActionPerformed

    private void btn_CancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarVendaActionPerformed
        limparTxtVenda();
    }//GEN-LAST:event_btn_CancelarVendaActionPerformed

    private void btn_RefreschCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreschCadastroActionPerformed
        Citem.lerLista(tbl_Lista);
    }//GEN-LAST:event_btn_RefreschCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelarVenda;
    private javax.swing.JButton btn_ConfimarVenda;
    private javax.swing.JButton btn_Pesquisa;
    private javax.swing.JButton btn_RefreschCadastro;
    private javax.swing.JButton btn_SelecionarItemVenda;
    private javax.swing.JComboBox combo_Tipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_EstoqueVenda;
    private javax.swing.JLabel lbl_IdVenda;
    private javax.swing.JLabel lbl_NomeVenda;
    private javax.swing.JLabel lbl_QuantidadeVenda;
    private javax.swing.JLabel lbl_TipoVenda;
    private javax.swing.JLabel lbl_ValorVenda;
    private javax.swing.JTable tbl_Lista;
    private javax.swing.JTextField txt_EstoqueVenda;
    private javax.swing.JTextField txt_IdVenda;
    private javax.swing.JTextField txt_NomeVenda;
    private javax.swing.JTextField txt_Pesquisa;
    private javax.swing.JTextField txt_QuatidadeVenda;
    private javax.swing.JTextField txt_TipoVenda;
    private javax.swing.JTextField txt_ValorVenda;
    // End of variables declaration//GEN-END:variables

    public void atualizatabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_Lista.getModel();
        tbl_Lista.setRowSorter(new TableRowSorter(modelo));
        Citem.lerLista(tbl_Lista);
    }

    public void limparTxtVenda() {
        txt_IdVenda.setText("");
        txt_NomeVenda.setText("");
        txt_TipoVenda.setText("");
        txt_EstoqueVenda.setText("");
        txt_ValorVenda.setText("");
        txt_QuatidadeVenda.setText("");
        txt_IdVenda.setEnabled(false);
        txt_NomeVenda.setEnabled(false);
        txt_TipoVenda.setEnabled(false);
        txt_EstoqueVenda.setEnabled(false);
        txt_ValorVenda.setEnabled(false);
        btn_ConfimarVenda.setEnabled(false);
        txt_QuatidadeVenda.setEnabled(false);
        txt_QuatidadeVenda.setEditable(false);

    }

    public void selecao() {

//////////////////////////////////////////////////////////////////////////////////////        
        //Seleciona Metodo ler Lista e listar na tabela
        if (combo_Tipos.getSelectedItem() == "Listar") {
            Citem.lerLista(tbl_Lista);
            System.out.println("seleção listar");
          
        }
//////////////////////////////////////////////////////////////////////////////////////
        //Seleciona Metodo Procurar por Nome
        if (combo_Tipos.getSelectedItem() == "Nome") {
            Citem.ListarPorNome(tbl_Lista, txt_Pesquisa);

        }
///////////////////////////////////////////////////////////////////////////////////////  
        //Seleciona Metodo Procurar por Tipo
        if (combo_Tipos.getSelectedItem() == "Tipo") {
            Citem.ListarPorTipo(tbl_Lista, txt_Pesquisa);
            System.out.println("entrou  " + combo_Tipos.getSelectedItem());
        }
        //Seleciona Metodo Procurar por Estoque Zerado
        if (combo_Tipos.getSelectedItem() == "Estoque Zerado") {
            Citem.ListarPorEstoqueZerado(tbl_Lista, txt_Pesquisa);

        }
        //Seleciona Metodo Procurar por Estoque Positivo
        if (combo_Tipos.getSelectedItem() == "Estoque Positivo") {
            Citem.ListarPorEstoquePositivo(tbl_Lista, txt_Pesquisa);

        }
        //Seleciona Metodo Procurar por Estoque Negativo
        if (combo_Tipos.getSelectedItem() == "Estoque Negativo") {
            Citem.ListarPorEstoqueNegativo(tbl_Lista, txt_Pesquisa);

        }

        txt_IdVenda.setEnabled(false);
        txt_TipoVenda.setEnabled(false);
        txt_EstoqueVenda.setEnabled(false);
        txt_ValorVenda.setEnabled(false);
    }

    public void buscarItemVenda() {
        int row = tbl_Lista.getSelectedRow();

        if (row != -1) {

            limparTxtVenda();

            txt_IdVenda.setText((String) tbl_Lista.getValueAt(row, 0).toString());
            txt_NomeVenda.setText((String) tbl_Lista.getValueAt(row, 1));
            txt_TipoVenda.setText((String) tbl_Lista.getValueAt(row, 2));
            txt_EstoqueVenda.setText((String) tbl_Lista.getValueAt(row, 3).toString());
            txt_ValorVenda.setText((String) tbl_Lista.getValueAt(row, 4).toString());

            btn_ConfimarVenda.setEnabled(true);
            txt_QuatidadeVenda.setEnabled(true);
            txt_QuatidadeVenda.setEditable(true);

        }

    }

    public void baixar() {
        int row = tbl_Lista.getSelectedRow();

        if (row != -1) {
            Item item = new Item();

            estoqueBaixa = Integer.parseInt(txt_EstoqueVenda.getText()) - Integer.parseInt(txt_QuatidadeVenda.getText());

            item.setId(Integer.parseInt(txt_IdVenda.getText()));
            item.setNome(txt_NomeVenda.getText());
            item.setTipo(txt_TipoVenda.getText());
            item.setEstoque(estoqueBaixa);
            item.setValor(Double.parseDouble(txt_ValorVenda.getText()));
            ItemDao.alterarItem(item);
            Citem.lerLista(tbl_Lista);

            JOptionPane.showMessageDialog(rootPane,
                    "Baixa realizada com sucesso !",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }
}
